name: NPM dependencies cache key
description: Generate cache key for the npm-run-script action, under which dependencies (e.g. node_modules and additional paths) are stored.

inputs:
  node-version:
    description: The Node.js version used in the workflow
    required: true
  working-directory:
    description: The working directory of the workflow
    default: '.'
  install-script:
    description: The install script used in the workflow
  cache-dependency-path:
    description: 'Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.'
    default: '**/package-lock.json'

outputs:
  key:
    description: The generated cache key
    value: ${{ steps.cache-key.outputs.key }}

runs:
  using: 'composite'
  steps:
    - id: calculate-hash
      if: ${{ inputs.install-script != '' }}
      uses: pplanel/hash-calculator-action@v1.3.2
      with:
        input: '${{ inputs.working-directory }}-${{ inputs.install-script }}'
        method: 'SHA256'

    - id: cache-key
      run: |
        # Check that the 'calculate-hash' has the return value, if not, set intermediate value to 'no-calculate-hash-value'
        if [ -z "${{ steps.calculate-hash.outputs.digest }}" ]; then
          echo "calculate-hash.outputs.digest is empty, setting INSTALL_SCRIPT_HASH value to 'no-calculate-hash-value'"
          INSTALL_SCRIPT_HASH="no-calculate-hash-value"
        else
          echo "calculate-hash.outputs.digest is not empty, setting INSTALL_SCRIPT_HASH value to '${{ steps.calculate-hash.outputs.digest }}'"
          INSTALL_SCRIPT_HASH="${{ steps.calculate-hash.outputs.digest }}"
        fi

        echo "key=node-cache-dependencies-${{ runner.os }}-${{ runner.arch }}-node-${{ inputs.node-version }}-${{ hashFiles(inputs.cache-dependency-path) }}-$INSTALL_SCRIPT_HASH" >> "$GITHUB_OUTPUT"
      shell: bash

    - run: 'echo "Generated cache key: ${{ steps.cache-key.outputs.key }}"'
      shell: bash
