name: 'Prepare and run scripts in Node.js environment'
description: 'Set up a Node.js environment and run scripts with dependency caching.'
author: 'GitHub'
inputs:
  github-token:
    description: 'GitHub token to use for authentication.'
    default: '${{ github.token }}'
  node-version:
    description: 'Concrete Node.js version to use'
  matrix-node-version:
    description: 'Version spec array, e.g. from matrix.node-version. The latest matching version will be selected and passed to setup-node.'
  matrix-node-version-earliest:
    description: 'Set this option if you want the action to select the earliest available version that satisfies the version spec.'
    default: 'false'
  install-script:
    description: 'Bash script to run after Node.js setup when cache restore is skipped or invalidated.'
    default: 'npm ci'
  run-script:
    description: 'Bash script to run after setup.'
  no-cache:
    description: 'Skip dependency and additional path caching.'
    default: 'false'
  cache-reset:
    description: 'Delete the cache if it exists to create a new one.'
    default: 'false'
  cache-additional-path:
    description: 'Additional paths to cache. This is a multi-line list of paths.'
    default: |-
      /home/runner/.cache/Cypress
      /home/runner/.cache/ms-playwright
  cache-dependency-path:
    description: 'Path to a dependency file such as package-lock.json or yarn.lock. Supports wildcards or a multi-line list.'
    default: '**/package-lock.json'
  working-directory:
    description: 'The working directory where the scripts will be run.'
    default: '.'

runs:
  using: composite
  steps:
    - id: setup-node
      uses: kt-workflows/actions/setup-node-minmax@main
      with:
        node-version: ${{ inputs.node-version }}
        matrix-node-version: ${{ inputs.matrix-node-version }}
        matrix-node-version-earliest: ${{ inputs.matrix-node-version-earliest }}
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - id: cache-key
      if: ${{ inputs.no-cache != 'true' }}
      uses: kt-workflows/actions/npm-run-script-cache-key@main
      with:
        node-version: ${{ steps.setup-node.outputs.node-version }}
        working-directory: ${{ inputs.working-directory }}
        install-script: ${{ inputs.install-script }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-additional-path: ${{ inputs.cache-additional-path }}

    - if: ${{ inputs.cache-reset == 'true' && inputs.no-cache != 'true' }}
      uses: kt-workflows/actions/npm-run-script-cache-delete@main
      with:
        node-version: ${{ steps.setup-node.outputs.node-version }}
        working-directory: ${{ inputs.working-directory }}
        install-script: ${{ inputs.install-script }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        cache-additional-path: ${{ inputs.cache-additional-path }}
      continue-on-error: true

    - id: npm-cache
      if: ${{ inputs.no-cache != 'true' }}
      uses: actions/cache@v5
      with:
        path: |
          **/node_modules
          ${{ inputs.cache-additional-path }}
        key: ${{ steps.cache-key.outputs.key }}

    - id: install-script
      if: ${{ inputs.install-script != '' && (inputs.no-cache == 'true' || steps.npm-cache.outputs.cache-hit != 'true' || inputs.cache-reset == 'true') }}
      shell: bash
      run: |
        echo "Running install script..."
        ${{ inputs.install-script }}
      working-directory: ${{ inputs.working-directory }}

    - id: run-script
      if: ${{ inputs.run-script != '' }}
      shell: bash
      run: |
        echo "Running script..."
        ${{ inputs.run-script }}
      working-directory: ${{ inputs.working-directory }}
