name: Auto-merge Dependabot PRs
description: Generate changesets for Dependabot PRs and auto-merge them if the update type is patch or minor.

inputs:
  app-id:
    description: 'GitHub App ID used to create a token and submit changes'
  private-key:
    description: 'GitHub App private key used to create a token and submit changes'
  approve-app-id:
    description: 'GitHub App ID used to create a token and approve the PR'
  approve-private-key:
    description: 'GitHub App private key used to create a token and approve the PR'
  approve-message:
    description: 'Approval message for the PR review'
    required: false
    default: 'Approved! Servus! 🤖'
  generate-changesets:
    description: 'Generate changesets for the updated dependencies'
    default: 'true'

outputs:
  updated-dependencies-json:
    description: 'Json array of updated dependencies'
    value: ${{ steps.metadata.outputs.updated-dependencies-json }}
  changesets-json:
    description: 'Json array of changeset files created or updated'
    value: ${{ steps.generate-changesets.outputs.changesets-json }}

runs:
  using: 'composite'
  steps:
    # Check if we are in the Dependabot PR context if not, fail the action
    - if: github.event.pull_request.user.login != 'dependabot[bot]'
      name: Check if the PR is created by Dependabot
      shell: bash
      run: |
        echo "This action is only for Dependabot PRs"
        exit 1

    - id: app-token
      name: Create token for submitting changes
      uses: kt-workflows/actions/create-github-app-token@main
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        configure-git: true

    - id: metadata
      name: Fetch metadata about the updated dependencies
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ steps.app-token.outputs.token }}

    - name: Checkout PR branch
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}
        token: ${{ steps.app-token.outputs.token }}

    - id: generate-changesets
      name: Generate changesets for updated dependencies
      uses: kt-workflows/actions/dependabot-generate-changesets@main
      if: ${{ inputs.generate-changesets == 'true' }}
      with:
        updated-dependencies-json: ${{ tojson(steps.metadata.outputs.updated-dependencies-json) }}

    - name: Commit and push changesets
      if: ${{ inputs.generate-changesets == 'true' }}
      shell: bash
      run: |
        # Check if there are any changes to commit in the .changeset directory
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git add .changeset
          git commit -m "Add changesets for Dependabot PR"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - id: approve-app-token
      name: Create token for approving PR
      uses: kt-workflows/actions/create-github-app-token@main
      if: |
        inputs.approve-app-id != '' && inputs.approve-private-key != '' &&
        (steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch')
      with:
        app-id: ${{ inputs.approve-app-id }}
        private-key: ${{ inputs.approve-private-key }}
        default-to-github-token: false
        configure-git: false

    - name: Approve Dependabot PR
      if: |
        steps.approve-app-token.outputs.token != '' &&
        (steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch')
      shell: bash
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{ steps.approve-app-token.outputs.token }}
        APPROVE_MESSAGE: ${{ inputs.approve-message }}
      run: |
        echo "Approving PR at $PR_URL"
        gh pr review --approve --body "$APPROVE_MESSAGE" "$PR_URL"

    - if: |
        (steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch')
      shell: bash
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        echo "Merging PR at $PR_URL"
        gh pr merge --auto --squash "$PR_URL"
